/**
 * GENERATED by scripts/build-art-assets.mjs — do not edit by hand.
 * AI-generated character art (docs/*.jpg) flood-filled to transparent,
 * resized to 512px, encoded as WebP, and inlined as base64 so the bundle
 * ships self-contained. Regenerate with: node scripts/build-art-assets.mjs
 */
export declare const CHARACTER_ASSETS: Record<string, string>;
